README.rst
openwisp_monitoring/device/models.py
openwisp_monitoring/device/settings.py
openwisp_monitoring/device/static/monitoring/css/monitoring.css
openwisp_monitoring/device/tests/test_models.py

[enhancement] Add UNKNOWN as Device monitoring status

---

tests/openwisp2/celery.py
tests/openwisp2/settings.py

[celerybeat] Fixed configuration issue

---

openwisp_monitoring/check/apps.py
openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/tests/test_models.py
openwisp_monitoring/check/tests/test_ping.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/monitoring/apps.py
openwisp_monitoring/monitoring/tests/test_models.py

[enhancement] Delete monitoring objects when devices are deleted

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/models.py

[refactor] Move get_device_data logic to DeviceData model #31

---

README.rst
openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/tests/test_ping.py
openwisp_monitoring/device/settings.py

Continuation of #42. Related to #24.

[check] Handled case in which IP is not present. 

---

openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/tests/test_ping.py

Fixed the issue as describe in its comment
and also added test cases to test this
enhancement
Fixes #24

[monitoring] Ping when Device IP is not present #24

---

.travis.yml
README.rst
openwisp_monitoring/check/tasks.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/apps.py
openwisp_monitoring/device/settings.py
openwisp_monitoring/device/signals.py
openwisp_monitoring/device/tasks.py
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/device/tests/test_recovery.py
openwisp_monitoring/device/utils.py
requirements.txt

[feature] Detect recoveries spontaneously #14

---

openwisp_monitoring/notifications/admin.py
openwisp_monitoring/notifications/tests/test_admin.py

[notifications] Added links for related fields #5

---

openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/settings.py
openwisp_monitoring/check/tests/test_ping.py
openwisp_monitoring/device/settings.py
tests/openwisp2/settings.py

Fixed the issue by moving the MANAGEMENT_IP_ONLY in device
settings to check module settings. and updating the test
cases
Fixes #59

[check] OPENWISP_MONITORING_MANAGEMENT_IP_ONLY issues #59

---

openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/device/models.py
openwisp_monitoring/device/schema.py
openwisp_monitoring/device/templates/admin/config/device/change_form.html
openwisp_monitoring/device/tests/test_models.py

[feature] Allow collecting ARP table information in DeviceData.data #34

---

openwisp_monitoring/device/settings.py
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/device/tests/test_settings.py
openwisp_monitoring/monitoring/tests/test_graphs.py
openwisp_monitoring/monitoring/tests/test_models.py

[tests] Pushing up coverage #71

---

.travis.yml
README.rst
openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tasks.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/device/tests/test_recovery.py
openwisp_monitoring/monitoring/models.py
openwisp_monitoring/monitoring/utils.py
tests/openwisp2/settings.py

Closes #4 
@nemesisdesign, this PR is not completely ready yet, I just wanted to confirm is this what you had in mind for the issue or any changes are required.

[feature] Listen to DeviceConnection.is_working changes #4

---

README.rst

[docs] Add available features section #84

---

openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/schema.py
openwisp_monitoring/device/templates/admin/config/device/change_form.html
openwisp_monitoring/device/tests/test_models.py

[feature] Added DHCP leases to device status #33

---

openwisp_monitoring/device/base/models.py
requirements.txt

[perf] Cached MAC lookup

---

openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/device/settings.py
openwisp_monitoring/monitoring/base/models.py

This is a nice feature from python 3 that we were not using and eases tracing backs crashes

[enhancement] Exception chaining

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tests/test_device_notifcations.py
openwisp_monitoring/device/tests/test_models.py

[change] Do not send recovery notification when is_working was None #138

---

openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/tests/test_api.py

Closes #56
Currently it looks like this. I think we can:
* add a column to the left for serial numbers
* Add a row stating `Histogram charts below` or something similar.
In the above image, the histogram chart's name is also `Histogram` (stating to avoid any confusion :sweat_smile: )
**PS**: One more thing I had changed top-fields in histogram configuration to 4.
* I am not sure about this line https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/device/api/views.py#L112 (in my opinion, histogram charts should not have data['x'] but the chart I have simulated for testing does have it so please confirm if I am correct regarding this.)

[charts] Add possibility to export histogram charts #56

---

openwisp_monitoring/db/backends/influxdb/client.py
openwisp_monitoring/db/backends/influxdb/queries.py
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/monitoring/base/models.py
tests/openwisp2/settings.py

Closes #143
Sorry, branch name is not following contributing guidelines.

[fix] String object has no attribute 'copy' in deep_merge_dicts #143

---

openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/templates/admin/chart_inline.html
openwisp_monitoring/monitoring/tests/test_charts.py

Closes #110
**PS**: There is a better and more full proof approach but it depends on the query below.

[fix] Fixed broken chart js in metric admin change form #110

---

README.rst
openwisp_monitoring/check/base/models.py
openwisp_monitoring/check/classes/base.py
openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/migrations/0001_initial.py
openwisp_monitoring/check/migrations/0003_create_ping.py
openwisp_monitoring/check/tasks.py
openwisp_monitoring/check/tests/test_models.py
openwisp_monitoring/check/utils.py
openwisp_monitoring/device/tests/test_recovery.py

Related to #54, #55. Breaks #123 into smaller PRs as per @PabloCastellano's suggestion.

[check] Refactor Check classes

---

.github/pull_request_template.md

Let me know what you think about the text. We can improve it now or later
Closes #89

feat(qa): use GitHub Pull Request templates #89

---

.travis.yml
Dockerfile
README.rst
docker-compose.yml
install-dev.sh
tests/docker-entrypoint.sh
tests/openwisp2/settings.py

[docker] Run openwisp-monitor in docker

---

openwisp_monitoring/monitoring/migrations/0017_merge_traffic_metrics_and_fill_metric_config.py

Issues/177 bugged monitoring.0017 migration

---

tests/openwisp2/routing.py

[tests] Added geo_routes from controller

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tests/test_device_notifications.py
openwisp_monitoring/monitoring/apps.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

Notifications texts

---

openwisp_monitoring/device/tests/test_device_notifications.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

[tests] Added support for read_redirect view in notification tests

---

README.rst
openwisp_monitoring/db/backends/influxdb/client.py
openwisp_monitoring/db/backends/influxdb/exception.py
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/db/exceptions.py
openwisp_monitoring/device/apps.py
openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/device/tests/test_recovery.py
openwisp_monitoring/device/utils.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/settings.py
openwisp_monitoring/monitoring/tasks.py

[timeseries] Make metric collection resilient to failures #166

---

install-dev.sh
openwisp_monitoring/check/apps.py
openwisp_monitoring/check/base/models.py
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/monitoring/charts.py
requirements-test.txt
setup.cfg
setup.py
tests/openwisp2/sample_check/models.py
tests/openwisp2/sample_check/tests.py
tests/openwisp2/sample_device_monitoring/models.py
tests/openwisp2/sample_monitoring/models.py

[qa] Updated code to isort 5

---

openwisp_monitoring/device/models.py
openwisp_monitoring/device/utils.py
tests/openwisp2/sample_device_monitoring/models.py

Temporary solution, may be obsoleted by
https://github.com/wq/django-swappable-models/pull/23

[refactor] Load BaseDevice using swappable

---

tests/openwisp2/settings.py

Flat json widget

---

README.rst
openwisp_monitoring/monitoring/configuration.py

Checks:
* Converted double to single quotes for fix introduced in https://github.com/openwisp/openwisp-monitoring/commit/2f60e22b10bda6d6049e2a6636d83a894c08e1ab and also made the changes in docs for the same.
* cpu --> CPU, ram --> RAM
* 90.0% --> 90% (however this change would be obsolete after #173)
* recovery notification message for resources metrics changed.
Closes #197

[chores] Improvements to PR #185

---

install-dev.sh
openwisp_monitoring/device/apps.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

Fixed notification sound.
Checks:
[Please follow this lint to see screenshots of the work. ](https://github.com/openwisp/openwisp-monitoring/pull/171#issuecomment-671075713)

[feature] Added notification setting from openwisp-notifications

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/monitoring/configuration.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

[tests] Fixed notifications test added in #189 + other minor improvements

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/static/monitoring/css/monitoring.css
openwisp_monitoring/device/tests/test_admin.py

[ux] Help user to find out what's wrong #172

---

openwisp_monitoring/check/migrations/0003_create_ping.py
openwisp_monitoring/check/migrations/0005_create_config_applied.py
openwisp_monitoring/check/tasks.py

[fix] Fixed create_ping and create_config migrations #205

---

requirements.txt

Checks:
Refer to https://github.com/openwisp/openwisp-monitoring/pull/227#discussion_r481200229
@nemesisdesign, do you think we should also pin down test dependencies?

[chores] Pin version for dependencies

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

Checks:
Allows to fix https://github.com/openwisp/openwisp-controller/issues/291.

[fix] Added can_be_updated to DeviceData

---

openwisp_monitoring/device/admin.py

[admin] Removing monkey patching in device admin #202

---

openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/tests/test_models.py
requirements.txt

[fix] Switched mac vendor lookup library #167

---

openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/device/tests/test_transactions.py

[fix] Do not trigger updates if health status is unknown

---

README.rst
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/tasks.py
openwisp_monitoring/monitoring/tests/test_models.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
requirements.txt

[monitoring] Rethink when check threshold #223

---

openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/schema.py
openwisp_monitoring/device/templates/admin/config/device/change_form.html
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/device/tests/test_api.py
tests/openwisp2/urls.py

[feature] Add support for mobile data to device status

---

README.rst

[docs] Relocate register notification types section

---

.github/workflows/ci.yml

- Added extra name option for influxdb image
- Change image to influxdb:alpine
- Remove unused redis
Fixes #265
Checks:

[ci] Fix CI build #265

---

.github/workflows/ci.yml

[fix] Removed apt-get upgrade because it cause issues

---

openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/monitoring/tests/test_models.py

Refactored one test which was giving me issues, but for some reasons it was never failing in the CI build.

[tests] Refactored test for InvalidChartConfigException

---

openwisp_monitoring/device/api/serializers.py
openwisp_monitoring/device/api/views.py
requirements.txt

[change] Updated the serializers imports #287

---

README.rst
openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/settings.py
openwisp_monitoring/device/tests/test_models.py

[feature] Clear management_ip when device goes offline #286

---

openwisp_monitoring/device/static/monitoring/js/device-map.js

In my environment i have a first location of type Polygon and two more of type Point.
In the map, the tooltip and popup only works only in markers of type Point, not in Polygon, also only works if the point is not inside the polygon.
Before:
https://user-images.githubusercontent.com/7120526/117864427-13fab200-b295-11eb-8cdd-6aed2c00e258.mp4
After:
https://user-images.githubusercontent.com/7120526/117864453-1b21c000-b295-11eb-9933-3af0986c1ec4.mp4
Now both are working.
I've also formatted the js code.
Checks:

[Fix] map tooltip and popup not working

---

README.rst
openwisp_monitoring/db/backends/influxdb/queries.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/schema.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/configuration.py
openwisp_monitoring/monitoring/static/monitoring/js/chart.js

[feature] Chart mobile (LTE/5G/UMTS/GSM) signal strength #270

---

openwisp_monitoring/device/static/monitoring/css/device-map.css
openwisp_monitoring/monitoring/apps.py
openwisp_monitoring/monitoring/tests/test_admin.py
requirements-test.txt
requirements.txt
tests/openwisp2/settings.py

Changes:
Registered menu groups.
Checks:
closes #299

[enhancement] Registered menu groups #299

---

requirements-test.txt
requirements.txt

[deps] Point utils to master

---

openwisp_monitoring/monitoring/tests/test_admin.py

close https://github.com/openwisp/openwisp-utils/issues/251

[test] Minor changes in test to fix failure

---

README.rst
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/signals.py
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/signals.py
openwisp_monitoring/monitoring/tasks.py
openwisp_monitoring/monitoring/tests/test_admin.py
openwisp_monitoring/monitoring/tests/test_models.py

[feature] Allow specify time of received timeseries data #298

---

openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

Made notification tests to only check changes introduced in
openwisp-monitoring
Checks:

[fix] Fixed notifications test

---

openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/tests/test_api.py

[fix] Fix device metrics not working with monitoring templates

---

README.rst
openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/settings.py
openwisp_monitoring/check/tests/test_ping.py
tests/openwisp2/sample_check/tests.py

[change] Added setting for making ping checks configurable #328

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tests/test_recovery.py

[tests] Added test for triggering device checks on recovery #338

---

README.rst
tests/openwisp2/settings.py

Closes #340
Checks:
Depends on https://github.com/openwisp/openwisp-controller/pull/591.

[tests] Added openwisp_ipam

---

run-qa-checks

[qa] Enable css and js linting checks #303

---

openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/tests/test_api.py
requirements.txt
tests/openwisp2/settings.py

[tests] Add tests for bearer authentication for Geo API endpoints

---

openwisp_monitoring/check/classes/ping.py

[refactoring] Migrate from Popen() to run() #300

---

openwisp_monitoring/device/models.py
openwisp_monitoring/utils.py
tests/openwisp2/sample_device_monitoring/models.py

[chores] Removed custom swappable load_model #266

---

openwisp_monitoring/check/classes/config_applied.py
openwisp_monitoring/device/apps.py
openwisp_monitoring/monitoring/base/models.py

Related to https://github.com/openwisp/openwisp-controller/pull/626

[change] Configured ignore connection notification reasons

---

README.rst
requirements.txt

[deps] Removed django-celery-email from requirements

---

README.rst
openwisp_monitoring/device/admin.py
openwisp_monitoring/device/tests/test_admin.py
requirements.txt
tests/openwisp2/settings.py

[feature] Allow importing / exporting devices #358

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/tests/test_admin.py

[fix] Fixed bug in deleting device with WiFiSessions #378

---

README.rst
openwisp_monitoring/device/admin.py
openwisp_monitoring/device/static/monitoring/css/wifi-session.css
openwisp_monitoring/device/static/monitoring/css/wifi-sessions.css
openwisp_monitoring/device/static/monitoring/js/wifi-session-inline.js
openwisp_monitoring/device/templates/admin/config/device/wifisession_tabular.html
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_admin.py
tests/openwisp2/sample_device_monitoring/templates/admin/config/device/wifisession_tabular.html

[feature] Added inline for WifiSession in DeviceAdmin #362

---

README.rst

[docs] Updated screenshot URL for traffic chart #384

---

openwisp_monitoring/device/templates/admin/config/device/change_form.html
openwisp_monitoring/device/tests/test_admin.py

[feature] Device status: make bridge members clickable #352

---

CHANGES.rst

(cherry picked from commit d49f0768a10eccb971f2362b7035ddb7a85b31f0)

[docs] Added changelog for 1.0.1 release

---

README.rst
tests/openwisp2/settings.py

This new feature was just added to OpenWISP Controller.

[change] Added admin_auto_filters to INSTALLED_APPS

---

openwisp_monitoring/check/migrations/0003_create_ping.py
openwisp_monitoring/check/migrations/0005_create_config_applied.py
openwisp_monitoring/check/migrations/0007_create_checks.py

Fixes #348.
Checks:
- N/A: I have written new test cases to avoid regressions (if necessary)
- N/A: I have updated the documentation (e.g. README.rst)

[fix] Fix creation of checks for existing devices #348

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tests/test_models.py
openwisp_monitoring/monitoring/apps.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/tasks.py
openwisp_monitoring/monitoring/tests/test_models.py

[change] Timeseries data is deleted when device is deleted #419

---

README.rst
openwisp_monitoring/check/classes/config_applied.py
openwisp_monitoring/check/settings.py
openwisp_monitoring/check/tests/test_models.py

[fix] Fixed `config_applied` check to a device flags it as PROBLEM #451

---

README.rst
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
openwisp_monitoring/views.py

[docs] Mentioned usage of custom daterange #453

---

openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js

[fix] Fixed blip caused by periodic chart reload #455

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/tests/test_admin.py

[fix] Fixed "Recover deleted devices" button visibility #470

---

.github/workflows/ci.yml

The dependency resolution issue should be solved.

[ci] Use latest pip version

---

CHANGES.rst
openwisp_monitoring/__init__.py

1.0.3 release

---

openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js

https://user-images.githubusercontent.com/56113566/212654558-637baf68-c185-46fb-9ad7-1236b935fc6d.mp4
Fixes #486
Checks:

[fix] Fixed daterangepicker label shows old dates #486

---

.github/workflows/ci.yml
tests/openwisp2/settings.py

Django 3.2, 4.0, Python 3.8, 3.9, 3.10.

[ci] Django 3.2, 4.0, Python 3.8, 3.9, 3.10

---

openwisp_monitoring/db/backends/influxdb/client.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/tasks.py
openwisp_monitoring/monitoring/tests/test_models.py

[change] Batch writes in Device metrics REST API #466

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/exportable.py

Needed to fix the build on https://github.com/openwisp/openwisp-network-topology/pull/160.

[refactor] Facilitate mocking of DeviceResource.fields

---

openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/tasks.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/device/writer.py

Closes https://github.com/openwisp/openwisp-monitoring/issues/484

[change] Moved device API view writing logic to background worker #484 

---

openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/schema.py
openwisp_monitoring/device/templates/admin/config/device/change_form.html
openwisp_monitoring/device/tests/__init__.py
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/device/tests/test_models.py

- **Depends on :** https://github.com/openwisp/openwrt-openwisp-monitoring/pull/118.
Closes #350
Checks:

[feature] Added wifi version capability to wifi interface status #350

---

openwisp_monitoring/device/schema.py

Fixing backward compatibility issues.

[fix] Htmode, allow additional properties

---

openwisp_monitoring/check/tasks.py
openwisp_monitoring/device/tasks.py
openwisp_monitoring/monitoring/tasks.py

[change] Added default timeout to celery tasks #474

---

openwisp_monitoring/monitoring/api/views.py
openwisp_monitoring/monitoring/tests/test_api.py

[change] Added Bearer Authentication to general monitoring API view

---

README.rst
openwisp_monitoring/device/api/filters.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/tests/test_api.py

[change:api] Migrated to openwisp-users REST API filters #510

---

.github/workflows/ci.yml

[ci] Updated coveralls in ci actions

---

.github/workflows/ci.yml
openwisp_monitoring/check/__init__.py
openwisp_monitoring/device/__init__.py
openwisp_monitoring/device/apps.py
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/monitoring/__init__.py
requirements-test.txt
requirements.txt
tests/openwisp2/sample_check/__init__.py
tests/openwisp2/sample_check/apps.py
tests/openwisp2/sample_device_monitoring/__init__.py
tests/openwisp2/sample_device_monitoring/apps.py
tests/openwisp2/sample_monitoring/__init__.py
tests/openwisp2/sample_monitoring/apps.py

- Dropped support for Django 4.0.0
- Dropped support for Python 3.7
- Bumped django-nested-admin~=4.0.2

[deps] Added support for Django 4.1.0 and 4.2.0 

---

.github/workflows/ci.yml
tests/openwisp2/local_settings.example.py
tests/openwisp2/settings.py

Related to https://github.com/openwisp/openwisp-utils/pull/351 and https://code.djangoproject.com/ticket/32935.

[fix] Workaround for spatialite issue on Ubuntu 22.04 LTS

---

openwisp_monitoring/device/static/monitoring/css/monitoring.css

[chores] Fixed CSS for device health checks field #521

---

openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/tests/test_ping.py

[fix] Fixed ping command "-i" > "-p" #527

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/tests/test_admin.py

[fix] Fixed WifiSession.stop_time formatting in django admin #525

---

openwisp_monitoring/device/static/monitoring/js/device-map.js

[change] Copy points out of world map only when needed #531

---

openwisp_monitoring/device/static/monitoring/js/device-map.js

[fix] Fixed bugs in map bounds #548

---

.github/workflows/ci.yml
README.rst
openwisp_monitoring/device/api/filters.py
openwisp_monitoring/device/api/serializers.py
openwisp_monitoring/device/api/urls.py
openwisp_monitoring/device/api/views.py
openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/monitoring/tests/test_models.py

[feature] Added API endpoint to return nearby devices #541

---

openwisp_monitoring/device/tests/test_api.py
openwisp_monitoring/device/writer.py
openwisp_monitoring/monitoring/configuration.py

[fix] Fixed unrecognized access technology exception

---

openwisp_monitoring/device/static/monitoring/css/daterangepicker.css

[chores] Made disabled dates lighter in daterangepicker

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/exportable.py
openwisp_monitoring/device/tests/test_admin.py

Related to https://github.com/openwisp/openwisp-controller/pull/852
Checks:

[chores] Updated import/export logic

---

.github/workflows/ci.yml

[ci] Fix coveralls build step

---

.github/workflows/ci.yml
openwisp_monitoring/device/apps.py
openwisp_monitoring/device/base/models.py
openwisp_monitoring/device/migrations/0009_update_device_status_for_disabled_critical_checks.py
openwisp_monitoring/device/tests/test_models.py

Implements and closes #576.
Checks:

[change] Set device status to unknown when critical checks are disaled

---

openwisp_monitoring/device/admin.py
openwisp_monitoring/device/tests/test_admin.py

[fix] Fixed WifiSessionAdmin.stop_time not following project timezone

---

.github/workflows/ci.yml

Run sample app after regular tests, combine coverage.

[ci] Run sample app after regular tests, combine coverage

---

.github/workflows/ci.yml

Run tests even on QA checks fail.

[ci] Run tests even on QA checks fail

---

openwisp_monitoring/device/apps.py
openwisp_monitoring/device/static/monitoring/js/device-map.js
openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
openwisp_monitoring/tests/test_selenium.py
tests/openwisp2/settings.py

Django admin should make API request to MONITORING_API_BASEURL.
Fixes https://github.com/openwisp/docker-openwisp/issues/329

[fix] Dashboard timeseries chart should respect MONITORING_API_BASEURL

---

.github/workflows/pypi.yml
setup.py

- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
[chores] Removed publish command from setup.py

[ci] Added PyPI release workflow

---

requirements-test.txt
requirements.txt

- Bumped openwisp-controller~=1.1.0
- Removed direct dependency on openwisp-utils since it is covered by openwisp-controller.

[deps] Upgraded openwisp-controller, removed openwisp-utils

---

CHANGES.rst
openwisp_monitoring/__init__.py

1.1.0 release

---

CHANGES.rst
openwisp_monitoring/__init__.py

1.1.1 release

---

openwisp_monitoring/tests/test_selenium.py

The test was failing due to changes in openwisp-controller.

[tests] Fixed "test_restoring_deleted_device" test

---

CHANGES.rst

[docs] Added changelog for 1.1.2 release

---

docs/user/settings.rst

Reordered the settings page to show the most critical settings first.

[docs] Reordered settings page

---

openwisp_monitoring/monitoring/configuration.py

Related to #623
I have extracted the following strings from emails. 
```
Subject: PROBLEM: openwisp-test-2 has too few WiFi clients
Description: The WiFi client count on openwisp-test-2 is below the expected threshold.
Subject: [openwisp.org] RECOVERY: openwisp-test-2 has WiFi clients connecting again
Description: The WiFi client count on openwisp-test-2 has increased and is now within the expected range.
```
--- 
```
Subject: [openwisp.org] PROBLEM: openwisp-test-2 has too many WiFi clients
Description: The WiFi client count on openwisp-test-2 exceeds the expected threshold.
Subject: [openwisp.org] RECOVERY: openwisp-test-2 WiFi client count has returned to normal
Description: The WiFi client count on  openwisp-test-2 has decreased and is now within the expected range.
```

[chores] Improved notification messages for WiFi Clients check #623

---

.github/workflows/ci.yml

[ci] Cache APT packages

---

openwisp_monitoring/check/base/models.py
openwisp_monitoring/check/migrations/0001_initial_squashed_0002_check_unique_together.py
openwisp_monitoring/check/migrations/0004_rename_active_to_is_active.py
openwisp_monitoring/check/settings.py
openwisp_monitoring/check/tasks.py
openwisp_monitoring/check/tests/test_ping.py
openwisp_monitoring/check/tests/test_utils.py
openwisp_monitoring/check/tests/test_wifi_client.py
openwisp_monitoring/device/base/models.py
tests/openwisp2/sample_check/migrations/0001_initial.py

Follow up of https://github.com/openwisp/openwisp-monitoring/pull/641.

[chores:refactor] Auto create checks

---

.github/workflows/ci.yml
openwisp_monitoring/device/tests/test_admin.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/migrations/0001_squashed_0023_alert_settings_tolerance_remove_default.py
requirements.txt
tests/openwisp2/routing.py
tests/openwisp2/sample_monitoring/migrations/0001_initial.py
tests/openwisp2/settings.py

Closes #645
- Upgraded django-nested-admin~=4.1.0
- Dropped support for Python < 3.9
- Dropped support for Django < 4.2

[deps] Added support for Django >=5.1,<5.3 and Python >=3.12, 3.14 #645

---

openwisp_monitoring/check/base/models.py
openwisp_monitoring/check/classes/base.py
openwisp_monitoring/check/classes/config_applied.py
openwisp_monitoring/check/classes/data_collected.py
openwisp_monitoring/check/classes/iperf3.py
openwisp_monitoring/check/classes/ping.py
openwisp_monitoring/check/tasks.py
openwisp_monitoring/check/tests/test_models.py
openwisp_monitoring/check/tests/test_ping.py

[feature] Log execution time of monitoring checks #658

---

openwisp_monitoring/check/tasks.py

[chores] Removed extra logging from perform check

---

docs/user/device-checks-and-alert-settings.rst
openwisp_monitoring/db/backends/influxdb/tests.py
openwisp_monitoring/monitoring/base/models.py
openwisp_monitoring/monitoring/tests/test_models.py
openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py

Fixes #666
(cherry picked from commit 2494ee2da6a7f683f00e0449848de8db569a63fc)

[fix] Don't evaluate threshold for historical data #666

---

CHANGES.rst
openwisp_monitoring/__init__.py
openwisp_monitoring/device/static/monitoring/js/device-map.js

Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
---
All commits in the master branch since 1.1.2 tag: https://github.com/openwisp/openwisp-monitoring/compare/1.1.2...master
Commits included for the 1.1.3 release: https://github.com/openwisp/openwisp-monitoring/compare/1.1.2...release/1.1.3

1.1.3 release

---

CHANGES.rst

GitHub Release: https://github.com/openwisp/openwisp-monitoring/releases/tag/1.1.3
PyPI Release: https://pypi.org/project/openwisp-monitoring/1.1.3/

[docs] Added changelog for Version 1.1.3
