openwisp/openwisp-monitoring

- openwisp_monitoring/check/tests/test_ping.py
- openwisp_monitoring/check/tests/test_utils.py
- openwisp_monitoring/device/tests/test_api.py
I just noticed that `mock` wasn't specified in `requirements-test.txt`, so I have updated the tests using `mock` module to now use `unittest.mock` which is built-in. Also, I have narrowed down the scope of import to just `patch` as that was only being used.
> [tests] Updating mock to unittest.mock

- openwisp_monitoring/check/migrations/0003_create_ping.py
Closes #16
`flake8` :heavy_check_mark: 
`isort`. :heavy_check_mark: 
Steps I took to check : 
1. After migration ran `python tests/manage.py migrate monitoring 0004`
2. Create few device using admin interface
3. Applied `0005_create_ping` migration,
4. Verified that ping checks were created.
> [monitoring] Added migration to create ping for existing devices. #16

- .travis.yml
- README.rst
- runflake8
- runisort
Closes #15
`pip` was erroring out due to incompatible requirements for `cryptography` module, so had to mention it in `requirements.txt`. [See for more info](https://travis-ci.com/github/TheOneAboveAllTitan/openwisp-monitoring/builds/158418833#L547)
Kindly suggest any other way to mitigate this problem.
@nemesisdesign please turn on Travis and Coveralls for this repository.
> [CI] Configured travis builds #15

- openwisp_monitoring/notifications/migrations/0003_default_permissions.py
I am not sure about whether permission given to operator is sufficient.
Closes #3 
`flake8` :heavy_check_mark: 
`isort`. :heavy_check_mark:
> [notification] Added default permissions for user groups. #3

- .travis.yml
- README.rst
- docker-compose.yml
- tests/openwisp2/settings.py
* Encourage usage of Docker and docker-compose, which allow developers to have the same versions independently of the distribution they use and keep their systems cleaner.
* Mention docker and link to install guide
* Create docker-compose.yml with pinned Redis and InfluxDB versions
* Run influxdb lighter alpine image in Travis
* Change default InfluxDB credentials to more descriptive ones
> [development] Improve install instructions and CI

- openwisp_monitoring/device/models.py
- openwisp_monitoring/device/schema.py
- openwisp_monitoring/device/static/monitoring/css/monitoring.css
- openwisp_monitoring/device/templates/admin/config/device/change_form.html
- openwisp_monitoring/device/tests/test_models.py
~~This is still WIP. The following need to be done:-~~
**PS**: The JSON type for `family` was provided as `integer` [here](http://netjson.org/rfc.html#addresses1) but it appeared visibly as `string` to me
Closes #30
> [monitoring] Allow to store IP addresses of interfaces in DeviceData.data #30

- openwisp_monitoring/monitoring/models.py
```
In [1]: Graph.objects.all()
Out[1]: <QuerySet [<Graph: Uptime>, <Graph: Packet loss>, <Graph: Round Trip Time>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>, <Graph: None>]>
In [10]: Graph.objects.first().label
Out[10]: 'Round Trip Time'
In [11]: Graph.objects.last().label
```
> [models] Fix Graph.label property

- openwisp_monitoring/device/models.py
- openwisp_monitoring/device/tests/test_models.py
An extract of what `ip neigh -json` returns in my device:
```
...
{
"dst": "fddc:c8c3:5b6c:0:8ca3:2665:625d:5921",
"dev": "br-lan",
"lladdr": "18:5e:0f:12:12:0e",
"state": [
"STALE"
]
},
{
"dst": "2001:db80::1",
"dev": "eth0.3",
"state": [
"FAILED"
]
},
...
```
> [fix] Sometimes mac_address key is not present in the dictionary

- .travis.yml
- openwisp_monitoring/device/admin.py
- openwisp_monitoring/monitoring/base/models.py
- requirements-test.txt
* Minor changes for qa-checks
* Bump `openwisp-utils` version to 0.5.0
* ~~Temporarily added `future` in travis until new `celery` release~~
* ~~Added `openwisp-utils` as a dependency.~~
**PS**: Realized that `openwisp-utils` is a dependency of `django-netjsonconfig`. So, it shouldn't be added but I didn't remove it from travis because `django-netjsonconfig` has locked `openwisp-utils` version to `0.4.5` (currently).
> [dependencies] Bump openwisp-utils version and few changes for qa-checks

- openwisp_monitoring/device/admin.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/notifications/tests/test_notifications.py
Link to related object was not present in notification email, therefore fixed that. 
These changes are also present in #93, but for a quick redressal I have made this patch. :smile:
> [monitoring] Related object URL in notification email

- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tests/test_models.py
The _get_or_create method of Metric took into account the "name" field when looking if the metric already exists, effectively preventing the metric from being renamed.
> [bug] Fixed error in _get_or_create when metrics are renamed

- openwisp_monitoring/monitoring/tests/test_graphs.py
Fixes #7
```
======================================================================                                                                                                                                                                    
FAIL: test_wifi_hostapd (openwisp_monitoring.monitoring.tests.test_graphs.TestGraphs)                                                                                                                                                     
----------------------------------------------------------------------                                                                                                                                                                    
Traceback (most recent call last): …
```
> [tests] Fix flaky test: test_wifi_hostapd #7

- README.rst
- openwisp_monitoring/check/base/models.py
- openwisp_monitoring/device/admin.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/base/models.py
- openwisp_monitoring/device/migrations/0002_devicemonitoring.py
- openwisp_monitoring/monitoring/admin.py
- openwisp_monitoring/monitoring/apps.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/charts.py
`ugettext_lazy` is currently a legacy method which comes with a warning that it's to be dropped in Django4.0. `gettext_lazy` is to be used in place of it from Django2.0 onwards.
Source: https://docs.djangoproject.com/en/3.0/_modules/django/utils/translation/
> [minor] Replace ugettext_lazy with gettext_lazy

- tests/openwisp2/settings.py
I have checked that celery logs aren't being duplicated but don't know for `py.warnings` log but it should be safe to have `propagate` disabled for it.
> [fix] Avoid log propagation when using root logger #131

- README.rst
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_device_notifcations.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/device/tests/test_recovery.py
- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
Related to https://github.com/openwisp/openwisp-notifications/issues/26
Notification Types Added:
- `unreachable_after_upgrade` - Notification specifically for a case like https://github.com/openwisp/openwisp-notifications/issues/26
- `device_up` - Notification when device becomes reachabel
- `device_down` - Generic notification when device is not reachable
When a device goes offline after an upgrade, two notifications are being generated
1. `threshold_crossed`
2. `unreachable_after_upgrade`
> [device] Added notification types for Device events

- openwisp_monitoring/check/classes/ping.py
- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/monitoring/tests/test_models.py
Closes #135
* `ContentType.objects.get_for_model()` can't be used in celery task as we can't pass a model as an argument to the shared task method (not JSON serializable).
* I am not sure whether to replace instances in migration scripts (skipped them currently). There are two such instances (one in main module and another in sample_app)
> [models] Use ContentType.objects.get_for_model #135

- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tests/test_models.py
Please refer to https://github.com/openwisp/openwisp-monitoring/pull/142#discussion_r444553485
> [timeseries] Refactor order parameter to only allow 'time' / '-time'

- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/monitoring/metrics.py
- openwisp_monitoring/monitoring/migrations/0014_merge_traffic_metrics.py
Closes #133
* I have created a migration script to delete traffic metrics (just in case there are too many interfaces so to avoid doing it manually)
* The new metric created automatically is able to communicate with the old measurement (thus the new chart is able to display old data, no data loss I mean :) )
> [metrics] Merge traffic metrics #133

- openwisp_monitoring/monitoring/admin.py
- openwisp_monitoring/monitoring/tests/test_admin.py
Fixed crash when viewing the Metric detail page. The description column was removed in 03097f8fba05644c784ab4321225f388a70104fd
```
Traceback (most recent call last):
File "/home/pablo/.virtualenvs/openwisp-monitoring/lib/python3.6/site-packages/django/contrib/admin/options.py", line 702, in get_form
return modelform_factory(self.model, **defaults)
File "/home/pablo/.virtualenvs/openwisp-monitoring/lib/python3.6/site-packages/django/forms/models.py", line 554, in modelform_factory
return type(form)(class_name, (form,), form_class_attrs)
File "/home/pablo/.virtualenvs/openwisp-monitoring/lib/python3.6/site-packages/django/forms/models.py", line 267, in __new__
raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (description) specified for Metric
```
> [admin] Fix crash due to showing unexisting description field

- openwisp_monitoring/device/admin.py
- openwisp_monitoring/device/tests/test_admin.py
Closes #53 
**PS** I have added check_inline.css as the default font-size of `Ping (Device: 08:00:27:04:8E:1C)` given by GenericTabularInline seems a bit small as can be seen in the pic above.
> [feature] Add Monitoring Checks section in Device Admin #53

- README.rst
- openwisp_monitoring/device/tasks.py
- openwisp_monitoring/device/tests/test_recovery.py
Added recovery argument to allow to be used also as a way to signal device issues.
Needed for https://github.com/openwisp/openwisp-network-topology/issues/75
Added mention of this integration in the README.
Will test this manually soon and then merge.
Checks:
> [fix] Do not call update_status directly if any check is present

- README.rst
- openwisp_monitoring/monitoring/__init__.py
- openwisp_monitoring/monitoring/tests/__init__.py
> [fix] Avoid register_chart, unregister chart import while apps are being loaded

- README.rst
- openwisp_monitoring/check/apps.py
- openwisp_monitoring/check/base/models.py
- openwisp_monitoring/check/classes/__init__.py
- openwisp_monitoring/check/classes/base.py
- openwisp_monitoring/check/classes/config_applied.py
- openwisp_monitoring/check/migrations/0005_create_config_applied.py
- openwisp_monitoring/check/settings.py
- openwisp_monitoring/check/tasks.py
- openwisp_monitoring/check/tests/test_models.py
- openwisp_monitoring/check/tests/test_ping.py
- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/metrics.py
- requirements-test.txt
> [feature] Add a check which inspects device configuration status periodically

- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_models.py
Do not send notifications on connection timed out failures, it means the device is offline.
> Ignore connection timed out errors

- openwisp_monitoring/check/tasks.py
- openwisp_monitoring/check/tests/test_utils.py
- openwisp_monitoring/device/tasks.py
- openwisp_monitoring/device/tests/test_models.py
Checks:
Steps followed,
1) Added a `time.sleep` of 20s in `perform_check`
2) Created a check (say `Test Resiliency`)
3) triggered `perform_check` for `Test Resiliency` check
4) while the task was frozen for **20s** (due to step 1), deleted the check `Test Resiliency`
5) After sleep duration got over celery worker info showed as below (*exception is caught* and *warning logged*):~
Closes #181
> [celery] Make tasks resilient to failures #181

- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tests/test_models.py
Checks:
* Fixed comparison and retrieval of metrics from timeseries database which was still taking place in seconds.
* Updated the two existing tests and added a new test which (tests tolerance and) will now fail without the fix.
* Double checked if any other instances were left out in the tests to be converted from seconds to minutest at https://github.com/openwisp/openwisp-monitoring/commit/791b7cd7b122d5078700484417c3d5a0f4b346de
Closes #219
> [fix] Fixed tolerance to be checked in minutes and not seconds #219

- openwisp_monitoring/check/base/models.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/models.py
- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/device/tests/test_recovery.py
- openwisp_monitoring/device/tests/test_transactions.py
- openwisp_monitoring/device/utils.py
- openwisp_monitoring/utils.py
- tests/openwisp2/sample_device_monitoring/models.py
- tests/openwisp2/sample_device_monitoring/tests.py
Many tasks were being called without transaction.on_commit,
which does not guarantee the tasks will be executed after
changes have been committed to the database, which in turn
leads to inconsistent results.
> [fix] Ensure background tasks are executed on transaction commit

- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_device_notifications.py
- tests/openwisp2/sample_device_monitoring/tests.py
Added object notification widget for DeviceAdmin which enables user
to disable notification for that device.
Checks:
> [chores] Made unregistering "default" notification type resilient to failure

- .travis.yml
- openwisp_monitoring/monitoring/base/models.py
Closes #225
Checks:
Work in Progress
* :warning: I found a potential bug while testing the front-end.
Traffic metric's metric admin is crashing when opened up :(
Below code is causing the issue (exception message is "it is not JSON serializable"), I couldn't figure out on a quick glance since all other metric admins are opening up and `ipdb` showed path followed and data serialized is almost similar. Will dig deeper.
https://github.com/openwisp/openwisp-monitoring/blob/7c66bada52b00237a986ed626b6c72c864d58c11/openwisp_monitoring/monitoring/base/models.py#L448-L453
* Django 3.1 also brings in left-pane in admin which I think shall be taken care of by **openwisp-utils==0.6.3**
* One more thing, observed a deprecation warning for `openwisp-controller`
> [deps] Add support for Django 3.1 #225

- openwisp_monitoring/device/tests/test_api.py
- requirements.txt
Closes #191
Checks:
Read the change log at https://github.com/influxdata/influxdb-python/blob/master/CHANGELOG.md#v530---2020-04-10.
There seem no breaking change and did a manual testing of the influxdb methods we are using in the tsdb client.
Also, there seems to be an improvement where we can pass in the time-precision of the timestamp we want in the latest version, noting here for future refs.
:warning: To be merged after #228.
> [deps] Upgrade InfluxDB python library to 5.3 #191

- openwisp_monitoring/check/classes/config_applied.py
- openwisp_monitoring/check/tests/test_models.py
- openwisp_monitoring/monitoring/base/models.py
Closes #195
This should be now taken care off by openwisp-controller (https://github.com/openwisp/openwisp-controller/pull/265).
Checks:
> [fix] Config Applied checks would be skipped when device config status is errored #195

- openwisp_monitoring/check/tests/test_models.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tests/test_models.py
- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
- if a metric is flapping during the tolerated interval, the system will not trigger status changes
- if a metric is not flapping, the system will trigger a status change, whether recovery or not
Before this change, recoveries did not respect the tolerance, causing the generation of many alerts on flapping metrics.
Closes #234
Checks:
> [change] Support tolerance in both directions #234

- .travis.yml
Temporary workaround to gain more time.
> [ci] Bind pip to 20.2.4 to avoid new dependency resolution algorithm

- openwisp_monitoring/check/migrations/0001_initial_squashed_0002_check_unique_together.py
- openwisp_monitoring/device/migrations/0001_squashed_0002_devicemonitoring.py
- openwisp_monitoring/monitoring/migrations/0001_squashed_0023_alert_settings_tolerance_remove_default.py
- tests/openwisp2/settings.py
Removed 'openwisp_monitoring.notifications'
Upgraded openwisp_utils latest version
Renamed `mac_address` to `mac` and `ip_address` to `ip` for improving consistency
Closes #233
Checks:
> [fix] Removed 'openwisp_monitoring.notifications'

- .github/workflows/ci.yml
The build is failing and I think it's because a new version of influxdb (2.0) has been released to the docker images and this new version has a stricter default configuration regarding authentication.
> [ci] Temporarily bind to influxdb:1.8.4-alpine

- README.rst
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_transactions.py
It does not make sense to trigger this check when the config is modified,
because the result will be always that config.status == 'modified'.
Moreover, due to the recent changes in openwisp-controller,
this action can now be executed also when a config has been just created
and m2m templates are added to it.
Rather than changing the code to check whether the signal is being
sent from m2m changes or not, it is a lot more useful to just
switch to the config_status_changed signal, which will trigger
the check also when the configuration is flagged as applied by
the system, making the check a lot more proactive.
Checks:
> [change] ConfigApplied triggered on config_status_changed instead of config_modified

- README.rst
- openwisp_monitoring/monitoring/configuration.py
- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
Added a default 5 minutes tolerance to CPU and memory.
Increased disk threshold value from 80% to 90% since some device models
have limited flash and would trigger the alert in many cases.
Will be testing this in the coming days.
Checks:
> [change] Changed default alert settings for disk, cpu, memory

- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/schema.py
- openwisp_monitoring/device/tests/test_api.py
- EC/IO = SNR
- Suport UMTS with missing RSSI
- fixed extra_values var not being reset for signal_quality
Checks:
> [fix] Fixed issues with mobile charts

- tests/openwisp2/settings.py
CHANNEL_LAYERS was not using REDIS_HOST env var
> [fix] Use REDIS_HOST in CHANNEL_LAYERS in test app

- openwisp_monitoring/monitoring/admin.py
- openwisp_monitoring/monitoring/tests/__init__.py
- openwisp_monitoring/tests/test_selenium.py
- requirements-test.txt
- tests/openwisp2/routing.py
Restorig a deleted device restores related DeviceMonitorig,
Metric and AlertSettings objects.
Related Check objects are not restored.
Closes #334
Checks:
> [fix] Restoring a deleted device restores related objects #334

- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
Bug:
The celery worker kept on retrying writing data to InfluxDB even
when the data points crossed rentention policy of InfluxDB. The
celery worker continued retrying such task indefinitely which
accumulated such tasks.
Checks:
> [fix] Skip retry for writing metrics beyond retention policy

- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/tests/test_api.py
- If data in charts is empty, then we can remove it from `API` response `(api/v1/monitoring/device/)` and it no longer visible on UI.
- For charts having empty data, we can check value of its `traces`.
Closes #349
Checks:
> [change] Removed charts which have empty data #349

- CHANGES.rst
- openwisp_monitoring/__init__.py
-   Removed hardcoded static URLs which created issues when static files
are served using an external service (e.g. S3 storage buckets)
-   Fixed ["migrate_timeseries" command stalling when measurements
exceeds retention policy][]
["migrate_timeseries" command stalling when measurements exceeds retention policy]:
https://github.com/openwisp/openwisp-monitoring/issues/401
> 1.0.1 release

- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
Bug:
In openwisp-notification 1.0.2, the operation for creating notification
settings when an organization is created is wrapped in transaction.on_commit.
TestMonitoringNotifications.test_cpu_metric_threshold_crossed was failing
because of this.
Fix:
Moved this test to a TransactionTestCase class.
> [fix] Fixed monitoring test failing due to openwisp-notification 1.0.2

- README.rst
- openwisp_monitoring/monitoring/configuration.py
- openwisp_monitoring/monitoring/static/monitoring/js/chart.js
- openwisp_monitoring/monitoring/tests/test_api.py
Fixes #87
Before        |  After
:-------------------------:|:-------------------------:
**After**
1. ![Screenshot (70)](https://user-images.githubusercontent.com/77020164/175225197-85c7348c-3177-4a12-bb1e-2cb1cd9237c7.png)
2. ![Screenshot (71)](https://user-images.githubusercontent.com/77020164/175228171-06ef3d7f-3fcf-4434-b516-82a690e99a0c.png)
**Changes**:
* All the data points have their data converted as per the range, and a particular chart has one specific unit.
* The percircles have their data converted and have different units as per the range.
* The side y-axis has a unit as same as what data points have.
**Demo**:
https://user-images.githubusercontent.com/77020164/175221352-22b969b6-05c2-499c-aac5-32bedc8369b4.mp4
Checks:
> [ux] Show size in (KB, MB or GB) adaptively in charts #87

- README.rst
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/settings.py
- openwisp_monitoring/device/utils.py
Added setting to configure default retention policy for the
timeseries database.
Related to https://github.com/openwisp/ansible-ow-influxdb/issues/12
Checks:
> [feature] Added setting to configure default retention policy

- openwisp_monitoring/db/backends/influxdb/queries.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/configuration.py
- openwisp_monitoring/monitoring/static/monitoring/js/chart.js
- openwisp_monitoring/monitoring/tests/test_api.py
- openwisp_monitoring/monitoring/tests/test_charts.py
- openwisp_monitoring/views.py
The traffic charts were showing the wrong total because of the
approximation (round-off) done in the backend to decrease the
the precision of values to two decimal places.
Since the adaptive feature already does this approximation
in the frontend, the rounding off is skipped from the backend.
Closes #415
Checks:
> [fix] Fixed traffic charts showing wrong traffic total #415

- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/tests/test_api.py
In some cases, the mobile signal info may be missing, therefore we need the code to be resilient and not crash in this case (simply do not try to write mobile signal data).
Checks:
> [fix] Fixed mobile signal missing case

- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_admin.py
- requirements-test.txt
- requirements.txt
The WifiSession pie chart on the dashboard was not filtering the
queryset by the related device's organization.
**Blockers**
Checks:
> [fix] Fixed WifiSession dashboard pie chart 

- README.rst
- openwisp_monitoring/check/base/models.py
- openwisp_monitoring/check/classes/iperf.py
- openwisp_monitoring/check/settings.py
- openwisp_monitoring/check/tasks.py
- openwisp_monitoring/check/tests/test_iperf.py
https://user-images.githubusercontent.com/56113566/187673896-1e358f5e-98bc-4afb-b3c4-21ef2750fb39.mp4
Closes #391
Checks:
Closes #439
> [feature] Added support for multiple iperf3 servers

- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/tests/test_api.py
The previous patch https://github.com/openwisp/openwisp-monitoring/commit/67bc8867e677b21de2d9c342670fd16fffb00b8d didn't take into account the case in which the `signal` key is missing entirely.
> Fixed device metric collection when mobile signal is missing

- README.rst
- openwisp_monitoring/check/settings.py
If OPENWISP_MONITORING_MANAGEMENT_IP_ONLY is not configured in the project settings, then it will fallback to the value of OPENWISP_CONTROLLER_MANAGEMENT_IP_ONLY setting. If OPENWISP_CONTROLLER_MANAGEMENT_IP_ONLY is also not present, then then it will fallback to ``True``.
Checks:
**Blockers**
> [change] Use OPENWISP_CONTROLLER_MANAGEMENT_IP_ONLY for OPENWISP_MONITORING_MANAGEMENT_IP_ONLY

- .github/workflows/ci.yml
As we already know, `gsoc22-iperf` [merged into master](https://github.com/openwisp/openwisp-monitoring/commit/11b31ffea2e32b93085e04b5fcb806682cbecc58), therefore now we can safely remove it from CI build.
> [ci] Removed `gsoc22-iperf` from CI build branches [skip ci]

- openwisp_monitoring/device/admin.py
- openwisp_monitoring/device/filters.py
- openwisp_monitoring/device/tests/test_admin.py
- openwisp_monitoring/monitoring/admin.py
- requirements.txt
Depens on https://github.com/openwisp/openwisp-users/pull/335.
This is not complete, a test fails.
**Blockers**
> [change] WiFi session admin: switched to autocomplete filters

- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
- openwisp_monitoring/views.py
-  Added custom zooming to monitoring charts. 
- `Zoom In` : To get a detailed view of all the monitoring charts for a specific time range. 
- `Zoom Out` : To reset all monitoring charts to the last selected time range.
https://user-images.githubusercontent.com/56113566/198017360-a56d1ba2-fe28-4738-9886-eb0851cc04dc.mp4
Closes #27
Checks:
> [feature] Added zooming graphs to provide a detailed view #27

- openwisp_monitoring/device/apps.py
When WiFi session monitoring is turned off, the application generated 500 error on the dashboard because the WiFi Client chart adds a quick link to WiFi Session admin.
Checks:
> [fix] Fixed General WiFi Client dashboard chart

- .github/workflows/ci.yml
- README.rst
- docker-compose.yml
- openwisp_monitoring/check/tests/test_iperf3.py
- openwisp_monitoring/check/tests/test_models.py
- openwisp_monitoring/check/tests/test_ping.py
- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/monitoring/tests/__init__.py
- openwisp_monitoring/monitoring/tests/test_charts.py
- openwisp_monitoring/monitoring/tests/test_models.py
- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
- runtests.py
- tests/influxdb.conf
- tests/openwisp2/settings.py
- Additional options can be specified to the TIMESERIES_DATABASE setting which are passed to the underlying backend library. This allows using UDP for writing to InfluxDB.
- "openwisp_monitoring.db.backends.influxdb.client.DatabaseClient.write" will use "InfluxDBClient.write_points" instead of "InfluxDBClient.write" because the former allows writing data using the UDP protocol.
Closes #458
Checks:
> [feature] Allowed specifying additional options for InfluxDB backend (UDP) #458

- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/base/models.py
- openwisp_monitoring/device/tests/test_models.py
WiFi sessions an of offline devices are closed when the threshold of device's critical metrics (ping) are crossed for longer than the tolerance set in metric's alert settings.
Closes #493
Checks:
> [change] Close WiFi Session respecting tolerance of critical metrics #493

- README.rst
- openwisp_monitoring/device/static/monitoring/css/wifi-sessions.css
- openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
Renamed date range widget label from last week, month and year to 7 days, 30 days and 365 days to avoid any misunderstandings in the future.
Closes #487
Checks:
> [change] Renamed daterangepicker widget labels #487

- openwisp_monitoring/device/tasks.py
- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_models.py
Ignore anything else which is coming from non access point interfaces.
Checks:
> [fix] Store only AP clients in WiFi Sessions

- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/device/writer.py
Type cast traffic data to integer to avoid type errors in InfluxDB.
Also avoid retrying any operation which fails with exception code 400.
Checks:
Fixes #512.
> [fix] Fixed traffic type issue

- openwisp_monitoring/tests/test_selenium.py
- requirements-test.txt
Similar to: https://github.com/openwisp/openwisp-network-topology/pull/187
and now we don't require pinning `urllib3` to version `1.x` in our project requirements (https://github.com/openwisp/openwisp-monitoring/pull/509/commits/9d3dd3a50272459fe4497261e99f48e58a1ba708).
> [deps] Upgraded selenium

- README.rst
- openwisp_monitoring/check/classes/base.py
- openwisp_monitoring/check/tasks.py
- openwisp_monitoring/check/tests/test_models.py
- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/api/views.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/base/models.py
- openwisp_monitoring/device/tasks.py
- openwisp_monitoring/device/tests/test_admin.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/device/writer.py
- openwisp_monitoring/monitoring/api/views.py
- openwisp_monitoring/monitoring/apps.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/migrations/__init__.py
- openwisp_monitoring/monitoring/tasks.py
- openwisp_monitoring/monitoring/tests/__init__.py
- openwisp_monitoring/monitoring/tests/test_api.py
- openwisp_monitoring/monitoring/tests/test_models.py
- openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
- openwisp_monitoring/settings.py
> [change] Reduced network calls in device metric flow #501

- openwisp_monitoring/device/api/views.py
> [fix] Fixed DeviceMetricView.post passing UUID object to celery task

- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tests/test_models.py
> [fix] Added error handling for IntegrityError in Metric._get_or_create #530

- .github/workflows/ci.yml
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/tests/test_admin.py
> [fix] Fixed slow query for WifiSession dashboard pie chart #528

- openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
> [fix] Prevent chart loading failure if timezone JS fails

- .stylelintrc.json
- openwisp_monitoring/device/static/monitoring/css/daterangepicker.css
- openwisp_monitoring/device/static/monitoring/css/device-map.css
- openwisp_monitoring/device/static/monitoring/css/monitoring.css
- openwisp_monitoring/monitoring/static/monitoring/css/chart.css
> [qa] Fixed stylelint issues

- requirements.txt
The urllib3 library is automatically pulled from requests which is now defined in openwisp-utils, so we don't need to have it defined here.
> [deps] Updated urllib3 and python-dateutil

- openwisp_monitoring/device/base/models.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/tasks.py
> [change] Renamed celery monitoring tasks with leading underscores #569

- README.rst
- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/db/backends/influxdb/tests.py
- openwisp_monitoring/device/apps.py
- openwisp_monitoring/device/static/monitoring/css/wifi-sessions.css
- openwisp_monitoring/device/static/monitoring/js/wifi-session-inline.js
- openwisp_monitoring/monitoring/api/views.py
- openwisp_monitoring/monitoring/base/models.py
- openwisp_monitoring/monitoring/configuration.py
- openwisp_monitoring/monitoring/static/monitoring/css/chart.css
- openwisp_monitoring/monitoring/static/monitoring/css/dashboard-chart.css
- openwisp_monitoring/monitoring/static/monitoring/js/chart-utils.js
- openwisp_monitoring/monitoring/static/monitoring/js/chart.js
- openwisp_monitoring/monitoring/templates/monitoring/paritals/chart.html
- openwisp_monitoring/monitoring/tests/__init__.py
- openwisp_monitoring/monitoring/tests/test_api.py
- openwisp_monitoring/monitoring/tests/test_charts.py
- openwisp_monitoring/monitoring/tests/test_configuration.py
- openwisp_monitoring/settings.py
- openwisp_monitoring/tests/test_selenium.py
- openwisp_monitoring/views.py
- Added option to define "summary_query" for metrics
- Added functionality to handle "GROUP by tags" clause to InfluxDB client
Related to #532
> [feature] Added organization filter to timeseries charts #532

- README.rst
- openwisp_monitoring/monitoring/configuration.py
This is needed to avoid confusion with the concept of system uptime.
Checks:
> [change:ux] Renamed Uptime chart to Ping Success Rate

- openwisp_monitoring/device/tests/test_models.py
The tests are failing due to an [upgrade to the jsonschema library in netjsonconfig](https://github.com/openwisp/netjsonconfig/commit/abc62e3b5dfd0b6e5d267e5190b07ce58baa62a6).
> [tests] Updated error messages from latest jsonschema 4.23.0

- openwisp_monitoring/device/tests/__init__.py
- openwisp_monitoring/device/tests/test_api.py
- openwisp_monitoring/device/tests/test_models.py
- openwisp_monitoring/device/writer.py
Fixes #595
- Both 'rx_bytes' and 'tx_bytes' are present in the statistics.
- Neither of them is None, which allows for zero values (as per the comment).
Closes #595
> [fix] Both 'rx_bytes' and 'tx_bytes' are present #595

- openwisp_monitoring/device/settings.py
- openwisp_monitoring/device/tests/test_settings.py
- N/A I have updated the documentation.
When using customized OPENWISP_MONITORING_HEALTH_STATUS_LABELS, forgetting to add the new deactivated status label after upgrading would cause a crash of the application during startup.
This fix provides a set of valid defaults which is always present and gets overridden with the custom labels.
N/A.
> [fix] Fixed backward compatibility issue with custom health status labels

- openwisp_monitoring/db/backends/influxdb/client.py
- openwisp_monitoring/monitoring/migrations/influxdb/influxdb_alter_structure_0006.py
Bug:
The delete query for migrating "traffic" data included WHERE clause which is not supported in InfluxDB.
Fix:
Migrate the "traffic" data at the end. Delete metrics only after migrating "traffic" data.
Fixes #626
> [fix] Fixed "migrate_timeseries" command

- openwisp_monitoring/monitoring/migrations/influxdb/influxdb_alter_structure_0006.py
Bug:
The READ_QUERY was failing if the measurement name starts with an integer.
> [fix] Wrap measurement name in double quotes in timeseries_migrate command

- openwisp_monitoring/device/api/filters.py
Closes https://github.com/openwisp/openwisp-monitoring/discussions/631
Adds isnull for stop_time in filters.py.
Afterwards one can filter by 'By stop time' --> No date via api.
> Add isnull to filters.py

- openwisp_monitoring/check/migrations/0007_create_checks.py
- openwisp_monitoring/device/migrations/0001_squashed_0002_devicemonitoring.py
Updated code in  data migrations which used "Model.objects.all()" to use "Model.objects.all()".
> [fix] Use "iterator" method instead of "all" to iterate over objects

- openwisp_monitoring/device/admin.py
The django-export-import dependency was upgraded in openwisp-controller which now allows selecting the columns during export operation.
Since this can cause issues during import of files with limited fields, we decided to rollback to the old implementation which exports all the fields of the device model.
Related https://github.com/openwisp/openwisp-controller/pull/915
> [chores] Do not allow selecting columns when exporting devices

- openwisp_monitoring/monitoring/configuration.py
Fixes #311
Closes #311.
Change label names as follows:
- Signal Strength -> Signal Strength (RSSI)
- Signal Power -> Signal Power (RSRP)
- Signal Quality -> Signal Quality (RSRQ)
- Signal to Noise Ratio -> Signal to Noise Ratio (SNR)
Please describe these changes.
> [change] Add metric names to signal chart labels #311

- docs/user/alerts.rst
- openwisp_monitoring/device/tests/test_admin.py
- openwisp_monitoring/monitoring/configuration.py
- openwisp_monitoring/monitoring/tests/test_admin.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
Change the default alert tolerance for the most commonly generated alerts to reduce noise.
On most prod instances we maintain, we must have at least 30 minutes of tolerance or we would incur in the generation of too many email alerts, which is not useful in most situations.
> [change] Changed default alert tolerances to reduce noise

- .github/workflows/ci.yml
- Add `gsoc25-map` in ci so that the tests can run PRs targeted to `gsoc25-map` branch
> [chores] Add gsoc25-map in ci

- openwisp_monitoring/device/tests/test_admin.py
- requirements.txt
Related to https://github.com/theatlantic/django-nested-admin/pull/273
> [tests] Fixed failing tests due to django-nested-admin

- openwisp_monitoring/device/static/monitoring/css/device-map.css
- openwisp_monitoring/device/static/monitoring/js/device-map.js
Set table width to 100% in map details for better layout. Adjust clustering to disable at zoom level 15 instead of 16, force tooltips to show on all viewport widths, and hide ECharts node labels at all zoom levels for a cleaner map display.
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/openwisp-monitoring/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
> [chores] Improve device map tooltip
